// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fawdwqtmuaujjicicjuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhd2R3cXRtdWF1amppY2ljanV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMjA0NzQsImV4cCI6MjA1ODU5NjQ3NH0.tlUN4y9sdVZRtgHeBPRUDF24TUgzT8JRaXgtBnHgkHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);